[[section-technical-risks]]
== Risks and Technical Debts

.Contents
In the following page we are going to identify, measure and priorize the risks and different technical debts that the project has.

.Risks
The following, is the list of risks found while developing the project

* SOLID: No previous knowledge about this technology until it was introduced to the team for this project.
* AngularJS: Not a familiar framework for any of the team members.
* Heroku: We are going to use this platform to host our SOLID server. We have to learn how it works and accept that the account has restrictions.
The principal restrictions that we have to face with Heroku are related to the number of queries that it allows with the free account that are 75 queries per user, app, hour.
Finally it was NOT used due to said limitations.
* GitHub Pages: web hosting service that must be used for deployment. First time for all team members.
* Typescript: As we researched, most SOLID apps are written using Typescript and we don't know anything about it. Adapting to it will be a risk, although it can't differ too much from Javascipt itself.
* Cucumber: In order to do the acceptance tests team members must learn Cucumber and Gherkin language.
* Protractor: Used to run Cucumber tests in a more visual way. Must learn the basics of this tool as well as how it works while used with Cucumber.
* Jest: Only one team member has experience with this tool. In the project, unit testing will be carried out using Jest.

.Technical debt
* Git: not a lot of experience with this tool.
* Bootstrap: none of the team members has previous experience with these libraries. It will not be such a huge risk due to the extensive guide and documentation provided online.
* Cucumber: just one member of the team has used Cucumber as a tool for writing customer acceptance tests. It is not classified as a severe risk.
* Jest: just one member of the team has used Jest as a tool for writing unit tests. It is not classified as a severe risk.

