sudo: required

language: bash

jobs:
  include:
    - stage: Generate documentation
      if: branch = master AND commit_message != "Updated GitHub Pages"
      before_script:
        - mkdir -p output
      script:
        - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -a toc=left -D /documents/output src/docs/*.adoc
      after_error:
        - docker logs asciidoc-to-html
      after_failure:
        - docker logs asciidoc-to-html
      after_success:
        - cd output
        - cp -R ../docs/images/ images
        - cd ..
        - git clone "https://github.com/Arquisoft/dechat_es1a.git"
        - cd dechat_es1a
        - rm -R docs
        - mv ../output/ dist/
        - git add .
        - git commit -m "Updated GitHub Pages"
        - git push --force --quiet "https://https://github.com/Arquisoft/dechat_es1a.git" master

    - stage: tests
      if: commit_message != "Updated GitHub Pages"
      script: echo "Implement tests"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      deploy:	
            provider: heroku	
            api_key:
                secure: 6af94bee-0789-41b6-9739-c2a35d324b4a
            app: dechates1a
            on:
               all_branches: true