dist: precise
language: node_js
sudo: false
node_js:
 - "stable"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start
  - "npm run webdriver 2>&1 &"
  - "sleep 3"
  - "echo webdriver started"
  - "npm start 2>&1 &"
  - "sleep 1"
  - "echo test app started"

script:
  - TEST_BROWSER_NAME=firefox npm test
